export const env = {
  ETHERSCAN_API_KEY: process.env.ETHERSCAN_API_KEY,
  SEPOLIA_PRIVATE_KEY: process.env.SEPOLIA_PRIVATE_KEY,
  SEPOLIA_RPC_URL: process.env.SEPOLIA_RPC_URL,
  COINMARKETCAP_API_KEY: process.env.COINMARKETCAP_API_KEY
}