/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as automation from "./automation";
export type { automation };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as vrf from "./vrf";
export type { vrf };
